// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: RecipeHashes.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecipeHashes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schemaVersion,proto3" json:"schemaVersion,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=lastUpdated,proto3" json:"lastUpdated,omitempty"`
	Blobs         []*RecipeHashes_Blobs  `protobuf:"bytes,3,rep,name=blobs,proto3" json:"blobs,omitempty"`
}

func (x *RecipeHashes) Reset() {
	*x = RecipeHashes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RecipeHashes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecipeHashes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeHashes) ProtoMessage() {}

func (x *RecipeHashes) ProtoReflect() protoreflect.Message {
	mi := &file_RecipeHashes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeHashes.ProtoReflect.Descriptor instead.
func (*RecipeHashes) Descriptor() ([]byte, []int) {
	return file_RecipeHashes_proto_rawDescGZIP(), []int{0}
}

func (x *RecipeHashes) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *RecipeHashes) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *RecipeHashes) GetBlobs() []*RecipeHashes_Blobs {
	if x != nil {
		return x.Blobs
	}
	return nil
}

type RecipeHashes_Blobs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sha string `protobuf:"bytes,1,opt,name=sha,proto3" json:"sha,omitempty"`
	Uid string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *RecipeHashes_Blobs) Reset() {
	*x = RecipeHashes_Blobs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RecipeHashes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecipeHashes_Blobs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeHashes_Blobs) ProtoMessage() {}

func (x *RecipeHashes_Blobs) ProtoReflect() protoreflect.Message {
	mi := &file_RecipeHashes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeHashes_Blobs.ProtoReflect.Descriptor instead.
func (*RecipeHashes_Blobs) Descriptor() ([]byte, []int) {
	return file_RecipeHashes_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RecipeHashes_Blobs) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

func (x *RecipeHashes_Blobs) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

var File_RecipeHashes_proto protoreflect.FileDescriptor

var file_RecipeHashes_proto_rawDesc = []byte{
	0x0a, 0x12, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xca, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65,
	0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x73,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x3c, 0x0a, 0x0b,
	0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x6c,
	0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x29, 0x0a, 0x05, 0x62, 0x6c,
	0x6f, 0x62, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x52, 0x65, 0x63, 0x69,
	0x70, 0x65, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x2e, 0x42, 0x6c, 0x6f, 0x62, 0x73, 0x52, 0x05,
	0x62, 0x6c, 0x6f, 0x62, 0x73, 0x1a, 0x2b, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x62, 0x73, 0x12, 0x10,
	0x0a, 0x03, 0x73, 0x68, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x68, 0x61,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x67, 0x75, 0x61, 0x72, 0x64, 0x69, 0x61, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_RecipeHashes_proto_rawDescOnce sync.Once
	file_RecipeHashes_proto_rawDescData = file_RecipeHashes_proto_rawDesc
)

func file_RecipeHashes_proto_rawDescGZIP() []byte {
	file_RecipeHashes_proto_rawDescOnce.Do(func() {
		file_RecipeHashes_proto_rawDescData = protoimpl.X.CompressGZIP(file_RecipeHashes_proto_rawDescData)
	})
	return file_RecipeHashes_proto_rawDescData
}

var file_RecipeHashes_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_RecipeHashes_proto_goTypes = []interface{}{
	(*RecipeHashes)(nil),          // 0: RecipeHashes
	(*RecipeHashes_Blobs)(nil),    // 1: RecipeHashes.Blobs
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_RecipeHashes_proto_depIdxs = []int32{
	2, // 0: RecipeHashes.lastUpdated:type_name -> google.protobuf.Timestamp
	1, // 1: RecipeHashes.blobs:type_name -> RecipeHashes.Blobs
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_RecipeHashes_proto_init() }
func file_RecipeHashes_proto_init() {
	if File_RecipeHashes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_RecipeHashes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecipeHashes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RecipeHashes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecipeHashes_Blobs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_RecipeHashes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_RecipeHashes_proto_goTypes,
		DependencyIndexes: file_RecipeHashes_proto_depIdxs,
		MessageInfos:      file_RecipeHashes_proto_msgTypes,
	}.Build()
	File_RecipeHashes_proto = out.File
	file_RecipeHashes_proto_rawDesc = nil
	file_RecipeHashes_proto_goTypes = nil
	file_RecipeHashes_proto_depIdxs = nil
}
